# В разработке: создайте папку data в корне проекта, затем создайте файл с именем [.config.yaml] внутри папки data
# Затем изменяйте или переопределяйте нужные настройки в [.config.yaml], а не в [config.yaml]
# Система сначала считывает конфигурацию из [data/.config.yaml]. Если чего-то нет — берёт из [config.yaml]
# Так вы защитите свои ключи и упростите настройку.
# Если вы используете панель управления, все эти настройки будут проигнорированы — настройте всё там

# #####################################################################################
# ############################# Основные настройки сервера ####################################
server:
  # Адрес и порт сервера (Server listening address and port)
  ip: 0.0.0.0
  port: 8000
  # Порт HTTP-сервера для OTA и визуального анализа
  http_port: 8003
  # Адрес WebSocket, который отправляется устройствам через OTA
  # По умолчанию генерируется автоматически, но при Docker или публичном доступе — укажите вручную
  websocket: ws://ваш_ip_или_домен:8000/xiaozhi/v1/
  # Адрес визуального анализа (для MCP Vision)
  vision_explain: http://ваш_ip_или_домен:8003/mcp/vision/explain
  # Часовой пояс (смещение в минутах)
  timezone_offset: +180  # Например, +180 = UTC+3 (Москва)
  # Настройки аутентификации
  auth:
    # Включить аутентификацию?
    enabled: false
    # Список токенов устройств (можно указать несколько)
    tokens:
      - token: "your-token1"
        name: "устройство-1"
      - token: "your-token2"
        name: "устройство-2"
    # Опционально: белый список MAC-адресов (все из списка подключаются без проверки токена)
    # allowed_devices:
    #   - "24:0A:C4:1D:3B:F0"

log:
  log_format: "<green>{time:YYMMDD HH:mm:ss}</green>[{version}_{selected_module}][<light-blue>{extra[tag]}</light-blue>]-<level>{level}</level>-<light-green>{message}</light-green>"
  log_format_file: "{time:YYYY-MM-DD HH:mm:ss} - {version}_{selected_module} - {name} - {level} - {extra[tag]} - {message}"
  log_level: INFO
  log_dir: tmp
  log_file: "server.log"
  data_dir: data

delete_audio: true
close_connection_no_voice_time: 120
tts_timeout: 10
enable_wakeup_words_response_cache: true
enable_greeting: true
enable_stop_tts_notify: false
stop_tts_notify_voice: "config/assets/tts_notify.mp3"

exit_commands:
  - "выход"
  - "стоп"
  - "закрыть"

xiaozhi:
  type: hello
  version: 1
  transport: websocket
  audio_params:
    format: opus
    sample_rate: 16000
    channels: 1
    frame_duration: 60

module_test:
  test_sentences:
    - "Привет, расскажи о себе"
    - "Какая сегодня погода?"
    - "Кратко объясни, что такое квантовые вычисления"

# Ключевые фразы для пробуждения
wakeup_words:
  - "привет, ассистент"
  - "эй, ассистент"
  - "привет, помощник"

# Адрес MCP-эндпоинта (если используется внешний)
mcp_endpoint: ваш_внешний_mcp_адрес

# Настройки плагинов
plugins:
  get_weather:
    api_host: "mj7p3y7naa.re.qweatherapi.com"
    api_key: "a861d0d5e7bf4ee1a83d9a9e4f96d4da"
    default_location: "Москва"  # ← Измените на ваш город

  get_news_from_chinanews:
    default_rss_url: "https://www.chinanews.com.cn/rss/society.xml"
    society_rss_url: "https://www.chinanews.com.cn/rss/society.xml"
    world_rss_url: "https://www.chinanews.com.cn/rss/world.xml"
    finance_rss_url: "https://www.chinanews.com.cn/rss/finance.xml"

  get_news_from_newsnow:
    url: "https://newsnow.busiyi.world/api/s?id="
    news_sources: "РИА Новости;Яндекс.Новости;Lenta.ru"

  home_assistant:
    devices:
      - Гостиная, лампа, switch.lamp
    base_url: http://homeassistant.local:8123
    api_key: ваш_ключ_home_assistant

  play_music:
    music_dir: "./music"
    music_ext:
      - ".mp3"
      - ".wav"
    refresh_time: 300

# ⚠️ ВАЖНО: Здесь были китайские имена — ЗАМЕНЕНЫ на русские
voiceprint:
  url:
  speakers:
    - "test1,Иван,Иван — программист"
    - "test2,Мария,Мария — менеджер продукта"
    - "test3,Алексей,Алексей — дизайнер"

# #####################################################################################
# ################################ Настройки модели ######################################

prompt: |
  Ты — голосовой помощник для умного дома. Говори спокойно, чётко и дружелюбно.
  Отвечай только на русском языке. Не используй китайский.
  Будь вежливым, кратким и полезным.

end_prompt:
  enable: true
  prompt: |
    Пожалуйста, закончи этот разговор фразой «Время летит так быстро» и несколькими эмоциональными словами.

# Модули, которые будут использоваться
selected_module:
  VAD: SileroVAD
  ASR: FunASR
  LLM: OllamaLLM  # ← ВАЖНО: Убедитесь, что используете OllamaLLM, а не qwen
  VLLM: ChatGLMVLLM
  TTS: EdgeTTS
  Memory: nomem
  Intent: function_call

Intent:
  nointent:
    type: nointent
  intent_llm:
    type: intent_llm
    llm: ChatGLMLLM
    functions:
      - get_weather
      - get_news_from_newsnow
      - play_music
  function_call:
    type: function_call
    functions:
      - change_role
      - get_weather
      - get_news_from_newsnow
      - play_music

Memory:
  mem0ai:
    type: mem0ai
    api_key: ваш_ключ_mem0ai
  nomem:
    type: nomem
  mem_local_short:
    type: mem_local_short
    llm: ChatGLMLLM

# ⚠️ ВАЖНО: Язык ASR — нужно указать русскую модель
ASR:
  FunASR:
    type: fun_local
    model_dir: models/SenseVoiceSmall  # ← Убедитесь, что модель поддерживает русский
    output_dir: tmp/
  SherpaASR:
    type: sherpa_onnx_local
    model_dir: models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17
    output_dir: tmp/
    model_type: sense_voice  # ← Эта модель поддерживает русский?
  # Рекомендация: используйте vosk-model-small-ru-0.22 для чистого русского ASR

VAD:
  SileroVAD:
    type: silero
    threshold: 0.5
    threshold_low: 0.3
    model_dir: models/snakers4_silero-vad
    min_silence_duration_ms: 200

# ⚠️ ВАЖНО: LLM должен быть на русском
LLM:
  OllamaLLM:
    type: ollama
    model_name: phi3  # ← Лучше использовать phi3, llama3 — они хорошо понимают русский
    base_url: http://localhost:11434

  # ❌ Избегайте qwen, если не хотите китайского
  # QwenLLM:
  #   type: ollama
  #   model_name: qwen:7b
  #   base_url: http://localhost:11434

# ⚠️ ВАЖНО: Выберите русский голос
TTS:
  EdgeTTS:
    type: edge
    voice: ru-RU-DmitriNeural  # ← Русский голос
    output_dir: tmp/

  # Примеры других русских голосов (если доступны)
  # voice: ru-RU-SvetlanaNeural
  # voice: ru-RU-AlyonaNeural

  # ❌ Избегайте китайских голосов
  # DoubaoTTS:
  #   voice: zh-CN-XiaoxiaoNeural  # ← Это китайский!

  # Рекомендуемый русский TTS
  Piper:
    type: piper
    voice: ru_RU-DmitriNeural
    output_dir: tmp/
    model_dir: models/piper/ru_RU-DmitriNeural

  # Другие TTS (настройте под себя)
  OpenAITTS:
    type: openai
    api_key: ваш_openai_ключ
    model: tts-1
    voice: onyx  # Поддерживает русский через OpenAI
    speed: 1
    output_dir: tmp/